- name: Copy httpd.conf
  copy:
    src: "{{ httpd_configuration_file }}"  
    dest: "/etc/httpd/conf/httpd.conf"

- name: restart httpd
  systemd:
    name: "httpd"
    state: restarted
    enabled: yes